// src/widgets/Header/ui/Header/Header.vue
<script lang="ts">
export interface HeaderProps {
  sticky?: boolean;
}
</script>

<script setup lang="ts">
import { CyrLogo } from '@shared/ui/Logo';
import styles from './Header.module.scss';

const { sticky = false } = defineProps<HeaderProps>();
</script>

<template>
  <header :class="[styles.header, { [styles.header_sticky]: sticky }]">
    <div :class="styles.header__container" class="container">
      <NuxtLink to="/">
        <CyrLogo />
      </NuxtLink>
      <slot />
    </div>
  </header>
</template>

// src/widgets/Header/ui/Header/Header.tsx
import styles from './Header.module.scss';
import { Logo } from 'shared/ui';
import { Menu } from 'widgets/Menu';
import { Link } from 'react-router-dom';
import { getRouteHome } from 'shared/consts/routers';

export const Header = () => {
  return (
    <div className={styles.header__container}>
      <Link to={getRouteHome()} className={styles.logo}>
        <Logo />
      </Link>
      <div className={styles.header__buttons}>
        <Menu />
      </div>
    </div>
  );
};
