// src/components/widgets/Header/ui/Header/Header.vue
<script setup lang="ts">
import { CyrLogo } from '@/components/shared/Logo';
import style from './Header.module.scss';

export interface HeaderProps {
  sticky?: boolean;
}

const { sticky = false } = defineProps<HeaderProps>();
</script>

<template>
  <header :class="[style.header, { [style.header_sticky]: sticky }]">
    <div :class="style.header__container">
      <NuxtLink to="/">
        <CyrLogo />
      </NuxtLink>
      <slot></slot>
    </div>
  </header>
</template>

// src/widgets/Header/ui/Header/Header.tsx
import styles from './Header.module.scss';
import { Logo } from 'shared/ui';
import { Menu } from 'widgets/Menu';
import { Link } from 'react-router-dom';
import { getRouteHome } from 'shared/consts/routers';

export const Header = () => {
  return (
    <div className={styles.header__container}>
      <Link to={getRouteHome()} className={styles.logo}>
        <Logo />
      </Link>
      <div className={styles.header__buttons}>
        <Menu />
      </div>
    </div>
  );
};
