// src/features/RegisterForm/ui/RegisterForm/RegisterForm.tsx
import { AuthContainer } from 'entities/Auth';
import { CyrButton, CyrError, CyrInput, CyrPasswordInput } from 'shared/ui';
import { registerFields } from '../../consts/registerFields';
import { Link } from 'react-router-dom';
import { useRegister } from '../../model/hooks/useRegister';
import { getRouteLogin } from 'shared/consts/routers';

export const RegisterForm = () => {
  const {
    registerField,
    onSubmit,
    responseError: error,
    isTouched,
  } = useRegister();

  return (
    <AuthContainer onSubmit={onSubmit}>
      <AuthContainer.Form>
        <h1>Sign up</h1>
        <CyrInput {...registerField(registerFields.name)} />
        <CyrInput {...registerField(registerFields.email)} />
        <CyrPasswordInput {...registerField(registerFields.password)} />
        {!isTouched && <CyrError message={error} />}
      </AuthContainer.Form>
      <AuthContainer.Buttons>
        <CyrButton type="submit">Create account</CyrButton>
      </AuthContainer.Buttons>
      <AuthContainer.Footer>
        <Link to={getRouteLogin()}>Already have an account? Login</Link>
      </AuthContainer.Footer>
    </AuthContainer>
  );
};

// src/features/RegisterForm/RegisterForm.vue
<script setup lang="ts">
import { CyrField, CyrPasswordField } from '@shared/ui/Input';
import { CyrForm } from '@shared/ui/Form';
import { CyrButton } from '@shared/ui/Button';
</script>

<template>
  <CyrForm>
    <h3>Sign up</h3>
    <CyrField name="name" label="Name" />
    <CyrField name="email" label="Email" />
    <CyrPasswordField name="password" label="Password" />
    <template #buttons>
      <CyrButton variant="solid" full> Create account </CyrButton>
    </template>
    <template #footer>
      <NuxtLink to="/auth/login"> Already have an account? Login </NuxtLink>
    </template>
  </CyrForm>
</template>
