// src/components/shared/CyrButton/CyrButton.vue
<script setup lang="ts">
import type { ButtonHTMLAttributes } from 'vue';
import style from './CyrButton.module.scss';

type ButtonVariants = 'solid' | 'outline' | 'transparent';
type ButtonTypes = ButtonHTMLAttributes['type'];

export interface CyrButtonProps {
  variant?: ButtonVariants;
  type?: ButtonTypes;
  icon?: boolean;
  full?: boolean;
}

const {
  variant = 'solid',
  type = 'button',
  icon,
  full,
} = defineProps<CyrButtonProps>();

const buttonClasses = computed(() => ({
  [style.button_full]: full,
  [style.button_icon]: icon,
  [style[`button_${variant}`]]: true,
}));
</script>

<template>
  <button :class="[style.button, buttonClasses]" :type="type">
    <slot></slot>
  </button>
</template>

// src/shared/ui/CyrButton/CyrButton.tsx
import styles from './CyrButton.module.scss';
import cn from 'classnames';

type TButtonProps = React.ButtonHTMLAttributes<HTMLElement> & {
  secondary?: boolean;
  icon?: boolean;
  className?: string;
};

export const CyrButton = ({
  children,
  secondary = false,
  icon = false,
  type = 'button',
  className,
  ...rest
}: TButtonProps) => {
  const classnames = cn(
    styles.button,
    secondary && styles.button_secondary,
    icon && styles.button_icon,
    className,
  );

  return (
    <button className={classnames} type={type} {...rest}>
      {children}
    </button>
  );
};
