// src/shared/ui/CyrAvatar/CyrAvatar.tsx
import styles from './CyrAvatar.module.scss';
import cn from 'classnames';

type TCyrAvatarProps = {
  image?: string | null;
  width?: number;
  name: string;
  dark?: boolean;
};

export const CyrAvatar = ({
  image,
  width,
  name,
  dark = false,
}: TCyrAvatarProps) => {
  return (
    <div
      className={cn(styles.avatar, dark && styles.avatar_dark)}
      style={{ fontSize: `${width}rem` }}
    >
      {image ? (
        <img src={image} />
      ) : (
        <div className={styles.avatar__text}>
          {name.trim()[0].toUpperCase()}
        </div>
      )}
    </div>
  );
};

// src/components/shared/CyrAvatar/CyrAvatar.vue
<script setup lang="ts">
import style from './CyrAvatar.module.scss';

interface CyrAvatarWithImage {
  image: string;
  text?: string;
}

interface CyrAvatarWithTitle {
  image?: string;
  text: string;
}

type CyrAvatarImageProps = CyrAvatarWithImage | CyrAvatarWithTitle;

const { image, text } = defineProps<CyrAvatarImageProps>();

const firstLetter = computed(() => text?.trim().charAt(0));
</script>

<template>
  <div :class="style.avatar">
    <img :src="image" :alt="text" :class="style.avatar__image" v-if="image" />
    <div :class="style.avatar__text" v-else>
      <span>{{ firstLetter }}</span>
    </div>
  </div>
</template>
