// src/features/LoginForm/ui/LoginForm/LoginForm.tsx
import { AuthContainer } from 'entities/Auth';
import { CyrButton, CyrError, CyrInput, CyrPasswordInput } from 'shared/ui';
import { useLogin } from '../../model/hooks/useLogin';
import { loginFields } from '../../consts/loginFields';
import { Link } from 'react-router-dom';
import { getRouterRegister } from 'shared/consts/routers';

export const LoginForm = () => {
  const {
    registerField,
    onSubmit,
    responseError: error,
    isTouched,
  } = useLogin();

  return (
    <AuthContainer onSubmit={onSubmit}>
      <AuthContainer.Form>
        <h1>Login</h1>
        <CyrInput {...registerField(loginFields.email)} />
        <CyrPasswordInput {...registerField(loginFields.password)} />
        {!isTouched && <CyrError message={error} />}
      </AuthContainer.Form>
      <AuthContainer.Buttons>
        <CyrButton type="submit">Login</CyrButton>
      </AuthContainer.Buttons>
      <AuthContainer.Footer>
        <Link to={getRouterRegister()}>
          Don&apos;t have an account? Sign up
        </Link>
      </AuthContainer.Footer>
    </AuthContainer>
  );
};

// src/features/LoginForm/LoginForm.vue
<script setup lang="ts">
import { CyrField, CyrPasswordField } from '@shared/ui/Input';
import { CyrForm } from '@shared/ui/Form';
import { CyrButton } from '@shared/ui/Button';
import { useForm } from 'vee-validate';
import { toTypedSchema } from '@vee-validate/valibot';
import { loginSchema } from '@entities/Auth';

interface LoginForm {
  email: string;
  password: string;
}

const { handleSubmit } = useForm<LoginForm>({
  validationSchema: toTypedSchema(loginSchema),
});

const onSubmit = handleSubmit((values) => {
  console.log(values);
});
</script>

<template>
  <CyrForm @submit="onSubmit">
    <h3>Welcome back!</h3>
    <CyrField name="email" label="Email" />
    <CyrPasswordField name="password" label="Password" />
    <template #buttons>
      <CyrButton type="submit" variant="solid" full> Login</CyrButton>
      <CyrButton variant="outline" full> Forgot password?</CyrButton>
    </template>
    <template #footer>
      <NuxtLink to="/auth/signup"> Don't have an account? Sign up</NuxtLink>
    </template>
  </CyrForm>
</template>
