// src/widgets/Header/ui/Header/Header.vue
<script lang="ts">
export interface HeaderProps {
  sticky?: boolean;
}
</script>

<script setup lang="ts">
import { CyrLogo } from '@shared/ui/Logo';
import styles from './Header.module.scss';

const { sticky = false } = defineProps<HeaderProps>();
</script>

<template>
  <header :class="[styles.header, { [styles.header_sticky]: sticky }]">
    <div :class="styles.header__container" class="container">
      <NuxtLink to="/">
        <CyrLogo />
      </NuxtLink>
      <slot />
    </div>
  </header>
</template>

// src/containers/Header/Header.tsx
import styles from './Header.module.scss';
import { ReactComponent as Logo } from '@/assets/icons/logo.svg';
import Menu from '@/containers/Menu/Menu';

const Header = () => {
  return (
    <div className={styles.header__container}>
      <div className={styles.logo}>
        <Logo />
      </div>
      <div className={styles.header__buttons}>
        <Menu />
      </div>
    </div>
  );
};

export default Header;
